import jsPDF from "jspdf";

export const addCommonHeaderFooter = async (doc, settings) => {
  const pageWidth = doc.internal.pageSize.getWidth();

  const companyName = settings?.name || "Company Name";
  const companyAddress = settings?.address || "N/A";
  const companyPhone = settings?.phone || "N/A";
  const companyEmail = settings?.email || "N/A";
  const companyWebsite = settings?.website || "N/A";
  const logoPath = settings?.logo ? `${import.meta.env.VITE_API_URL}${settings.logo}` : null;

  const urlToDataUrl = async (url) => {
    try {
      const response = await fetch(url);
      const blob = await response.blob();
      return await new Promise((resolve) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result);
        reader.readAsDataURL(blob);
      });
    } catch (err) {
      console.log("Logo load failed:", err);
      return null;
    }
  };

  let logoDataUrl = null;
  if (logoPath) logoDataUrl = await urlToDataUrl(logoPath);

  doc.setFillColor(0, 0, 0);
  doc.rect(0, 0, pageWidth, 35, "F");

  if (logoDataUrl) {
    const imgType = logoDataUrl.startsWith("data:image/png") ? "PNG" : "JPEG";
    doc.addImage(logoDataUrl, imgType, 15, 5, 25, 15); 
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text(companyName, pageWidth / 2, 12, { align: "center" }); 

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(`${companyWebsite} | ${companyPhone} | ${companyEmail}`, pageWidth / 2, 23, { align: "center" });
  doc.text(`Address: ${companyAddress}`, pageWidth / 2, 28, { align: "center" });

  doc.setDrawColor(180);
  doc.line(10, 31, pageWidth - 10, 31);

  return doc;
};

export const addCommonFooter = (doc, settings) => {
  const pageWidth = doc.internal.pageSize.getWidth();
 
  const companyName = settings?.name || "Company"; 
  
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text(`This report is generated by ${companyName}`, pageWidth / 2, 287, { align: "center" });
  return doc;
};